require('settings')
require('packer-config')
require('nvim-tree-config')
-- require('colourschemes-config.nightfox')
-- require('colourschemes-config.github')
-- require('colourschemes-config.onedark')
require('colourschemes-config.gruvbox')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('notify-config')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('transparent-config')
require('nvim-autopairs-config')
require('greeter-config')
require('colorizer-config')
require('toggle-term-config')
require('code-runner-config')
